### ISSUE TITLE
Object doesn't support property or method 'MoveHeadPosition'

### ISSUE THREAD

**Issue by montekalisch** [MistySampleSkills/Wander#1]
Just logging that I tried this with our new Misty and received an exception. I haven't had a chance to debug further.

Robot Version: 1.5.3.9838
Sensory Services Version: 1.5.3
Windows OS Version: 10.0.17763.253

**Comment by johnathanDOS** [comment]
Hi @montekalisch,

The MoveHeadPosition method was recently removed from the JS API, and it looks like we'd missed updating this piece of sample code to reflect that. (There's [another conversation](https://github.com/MistySampleSkills/LooksAtFace/pull/3
) about this in a different skill repo if you'd like to learn more). I'm going through today to make sure these all have current API methods. I've just [updated this repo](https://github.com/MistySampleSkills/Wander/commit/cf890a45f42d5c229bc1eb378b2e17cbc54198ce); could you try it out with the changes and let us know if it's still not working for you? I'm going to close the issue for now, but will reopen it if there's still trouble.

(PS - we met at ISTE in Philadelphia. Glad you got your robot at last! Look forward to seeing you around the forums :))

**Comment by montekalisch** [comment]
Thanks, Johnathan, for the fix. 

And of course I remember meeting you at ISTE. We are so excited about Misty. I'm playing with her now. I also recently moved to Denver. Love to come see you guys at some point to learn more.
